config/routes.rb
Rails.application.routes.draw do
  root 'asks#new'

  post 'asks/check'

  post  'asks/thanks'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ask.rb
class Ask < ApplicationRecord
  validates :name, presence: true, length: { in: 1..160 }
  validates :email, presence: true
  validates :content, length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/asks_controller.rb
class AsksController < ApplicationController
  
 def new 
   @ask = Ask.new
 end

  def check

   
    @ask = Ask.new(ask_params)
    if @ask.save
      render "check"
    else
      render :new
    end


  end

  def thanks
    @ask = Ask.new(ask_params)
    AskMailer.get_email(@ask).deliver_now
  end


  private

    def ask_params
      params.require(:ask).permit(:name, :email, :relationship, :content)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/asks_helper.rb
module AsksHelper
end

app/views/asks/check.html.erb
<div class="confirmPage">
  <div class='container'>
    <h1 class="confirmPage_title">Inquiry contents</h1>
    <%= form_with model: @ask, url: asks_thanks_path, method: :post, local: true do |f| %>
      <div class="confirmForm_item">
        <h3>Annoying people name </h3>
        <div>
          <%= f.hidden_field :name %>
          <%= @ask.name %>
        </div>
      </div>
      <div class="confirmForm_item">
        <h3>The person's email</h3>
        <div>
          <%= f.hidden_field :email %>
          <%= @ask.email %>
        </div>
      </div>
      <div class="confirmForm_item">
        <h3>Relation with the person</h3>
        <div>
          <%= f.hidden_field :relationship %>
          <%= @ask.relationship %>
        </div>
      </div>
      <div class="confirmForm_item">
        <h3>Something you wanto tell</h3>
        <div>
          <% if @ask.content.empty? %>
           Nothing especially
          <% else %>
           <%= @ask.content %>
          <% end%>
          <%= f.hidden_field :content %>
        </div>
      </div>
      <div class="text-center">
        <%= link_to "Back", root_path, class: "btn btn-info"%>
        <%= f.submit 'Submit', :class => 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/asks/new.html.erb
<div class='topPage'>
  <div class="container">
    <h1>Telling the annoing harasment</h1>
    <p>Tellign the harrsament instead of you 
    </p>
    <%= form_with(model: @ask, url: asks_check_path, local: true) do |f| %>
    <% if @ask.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <strong>Attention!! some information is blank</strong>
    <ul>
      <% @ask.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
      <div class="form-group">
       <%= f.label :name %>
        <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "name" %>
      </div>
      <div class="form-group">
       <%= f.label :email %>
        <%= f.text_field :email, autofocus: true, class: "form-control", placeholder: "e-mail" %>
      </div>
      <div class="form-group">
        <%= f.label :relationship %>
        <%= f.select(:relationship, [ ["Boss", "Boss"], ["President", "President"]], {}, class: "form-control") %>
      </div>
      <div class="form-group">
        <%= f.label :content %>
        <%= f.text_area :content, class: "form-control", placeholder: "Write something you want to tell" %>
      </div>
       <div class="text-center"><%= f.submit 'checking page', class: 'btn btn-primary' %></div>
    <% end %>
  </div>
</div>

app/views/asks/thanks.html.erb
<div class='thanksPage'>
  <div class='container'>
    <p class="thanksPage_message">Thank you fro inquiring</p>
    <div class="text-center"><%= link_to "Back to the top page", root_path, class: "btn btn-primary" %></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Telling</title>
    <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1">
 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>